### ISSUE TITLE
Turn off hyperref borders when in user annotation mode

### ISSUE THREAD

**Issue by andrewhead** [allenai/scholar-reader#70]
To avoid biasing annotators from just annotating all citations that have green hyperref borders around them, turn off the hyperref citation highlights when user annotation mode is entered. This might mean selectively applying this style to hyperref `.linkAnnotation` elements when the annotation mode is entered.

```css
section.linkAnnotation {
  border: none !important;
  cursor: text !important;
}
```
